spring.datasource.url=jdbc:postgresql://localhost:5432/cabinet_db
spring.datasource.username=postgres
spring.datasource.password=odoo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.frontend-url=http://localhost:4200

# Auth service
auth.service.url=http://localhost:8081

# Email Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=comptaAssist2026@gmail.com
spring.mail.password=ebib gfse rutm kuyn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

app.internal-secret=comptaassist-internal-secret-2024

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

docuseal.api-token=K9FURbHhn7TNcSXMSu1rJ4DC6L8j4DbmQVNf13Ryhau

# URL API DocuSeal self-hosted
docuseal.base-url=http://localhost:3003/api

# Gotenberg (port 3002)
gotenberg.url=http://localhost:3002

# Nom du cabinet affiche dans les PDFs
app.cabinet.nom=ComptaAssist Cabinet

trello.api.key=2836b55b5302711b4f1c51ff480304b3
trello.api.token=ATTA3bc245fee8c1806f1b1a57f344d8306baee025f6379e5f3c70a9dc3dea48e633B1127235
trello.board.id=6a3656b8a88f8c08109dd1de
trello.list.non-demarre=6a3656b9a88f8c08109dd20a
trello.list.en-cours=6a3656b9a88f8c08109dd20b
trello.list.a-jour=6a3656b9a88f8c08109dd20c


livekit.api-key=devkey
livekit.api-secret=secretsecretsecretsecretsecret32
chat.service.url=http://localhost:8088

local.uploads.path=C:/ComptaAssisst/compta/cabinet-service/uploads