spring.datasource.url=jdbc:postgresql://localhost:5432/fiscal_rag_db
spring.datasource.username=postgres
spring.datasource.password=odoo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Python RAG service
python.rag.url=http://localhost:8001
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# JWT (meme secret que auth-service)
jwt.access-token-expiration=86400000

# Desactiver Eureka pour l'instant
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
