spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Routes via Eureka (load-balanced)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# AUTH
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# CABINET
spring.cloud.gateway.routes[1].id=cabinet-service
spring.cloud.gateway.routes[1].uri=lb://CABINET-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/cabinets/**

# DOCUMENT
spring.cloud.gateway.routes[2].id=document-service
spring.cloud.gateway.routes[2].uri=lb://DOCUMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/documents/**,/api/internal/**

# FISCAL-RAG
spring.cloud.gateway.routes[3].id=fiscal-rag-service
spring.cloud.gateway.routes[3].uri=lb://FISCAL-RAG-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/fiscal/**

# FACTURE
spring.cloud.gateway.routes[4].id=facture-service
spring.cloud.gateway.routes[4].uri=http://localhost:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/factures-cpc/**,/api/bilan/**,/api/liens-upload/**,/api/ecritures/**

# TVA
spring.cloud.gateway.routes[5].id=tva-service
spring.cloud.gateway.routes[5].uri=http://localhost:8087
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/tva/**

# CHAT
spring.cloud.gateway.routes[6].id=chat-service
spring.cloud.gateway.routes[6].uri=http://localhost:8088
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/chat/**,/ws-chat/**

# CORS global
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true